# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toast', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='extpub_key',
            new_name='extpub',
        ),
    ]
