# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 14:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_processor', models.CharField(choices=[('OK', 'OKPay'), ('PM', 'Perfect Money'), ('PZ', 'Payza')], help_text='The payment processing service that was used to make this transaction.', max_length=255)),
                ('payment_processor_id', models.CharField(help_text='The transaction id provided by the payment processor', max_length=255)),
                ('tx_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], help_text='The type of transaction this is. It is always in reference to the Nu currency.', max_length=255)),
                ('currency', models.CharField(choices=[('NBT', 'NuBits')], help_text='The Nu currency this transaction relates to.', max_length=255)),
                ('amount', models.DecimalField(decimal_places=6, help_text='The amount of Nu currency transacted.', max_digits=20)),
                ('price', models.DecimalField(decimal_places=6, help_text='The total price that this transaction is worth', max_digits=20)),
                ('address', models.CharField(help_text='The Nu address associated with this transaction. This will either be used to receive funds from a customer or be provided by a customer to receive their Nu tokens. ', max_length=255)),
                ('complete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='butter_txs', related_query_name='butter_tx', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
