# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='price',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='payment_processor_id',
            field=models.CharField(blank=True, help_text='The transaction id provided by the payment processor', max_length=255),
        ),
    ]
