# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butter', '0002_auto_20160611_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='address',
            field=models.CharField(blank=True, help_text='The Nu address associated with this transaction. This will either be used to receive funds from a customer or be provided by a customer to receive their Nu tokens. ', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='payment_processor',
            field=models.CharField(choices=[(b'OK', b'OKPay')], help_text='The payment processing service that was used to make this transaction.', max_length=255),
        ),
    ]
